window.SITE_DATA = {
  "stats": {
    "papers": 5,
    "projects": 110,
    "mirrors": 72
  },
  "papers": [
    {
      "title": "MiddleOut Lattice: Lossless Compression of LLM Artefacts with Codec-Aware Tensor Packing",
      "version": "research draft",
      "status": "technical report + public demo",
      "summary": "A new lossless compression project that combines per-file and per-block codec selection, a compressed model store, and a public demo linked from the GitHub Pages research index.",
      "pdf": "papers/middleout-lattice-paper.pdf",
      "tex": "Deliverables/middleout-lattice/middleout-lattice-paper.tex",
      "tags": [
        "lossless compression",
        "LLM artefacts",
        "codec-aware packing"
      ],
      "primary": false
    },
    {
      "title": "KVQuant: Adaptive Long-Context KV-Cache Compression for Memory-Bounded LLM Inference",
      "version": "v3 — 32-page manuscript",
      "status": "submission-ready preprint",
      "summary": "The most complete version: rate-distortion framing, sink-aware allocation, head/layer coupling, benchmark plan, failure analysis, and a full appendixed derivation.",
      "pdf": "papers/kvquant-paper-ultradeep-v3.pdf",
      "tex": "Deliverables/kvquant-author-pack/kvquant-paper-ultradeep-v3.tex",
      "tags": [
        "LLM inference",
        "quantisation",
        "memory systems"
      ],
      "primary": true
    },
    {
      "title": "KVQuant: Adaptive Long-Context KV-Cache Compression for Memory-Bounded LLM Inference",
      "version": "v2 — extended draft",
      "status": "research manuscript",
      "summary": "A strong intermediate draft with an expanded mathematical treatment and a more detailed systems analysis.",
      "pdf": "papers/kvquant-paper-ultradeep-v2.pdf",
      "tex": "Deliverables/kvquant-author-pack/kvquant-paper-ultradeep-v2.tex",
      "tags": [
        "draft",
        "systems",
        "compression"
      ],
      "primary": false
    },
    {
      "title": "KVQuant: Adaptive Long-Context KV-Cache Compression for Memory-Bounded LLM Inference",
      "version": "deep draft",
      "status": "technical report",
      "summary": "An earlier deep write-up, useful for tracing how the mathematics and implementation story evolved.",
      "pdf": "papers/kvquant-paper-ultradeep.pdf",
      "tex": "Deliverables/kvquant-author-pack/kvquant-paper-ultradeep.tex",
      "tags": [
        "technical report",
        "implementation"
      ],
      "primary": false
    },
    {
      "title": "KVQuant: Adaptive Long-Context KV-Cache Compression for Memory-Bounded LLM Inference",
      "version": "concise preprint",
      "status": "shorter paper version",
      "summary": "A shorter, crisper manuscript if you want the idea in a more compact form.",
      "pdf": "papers/kvquant-paper.pdf",
      "tex": "Deliverables/kvquant-author-pack/kvquant-paper.tex",
      "tags": [
        "preprint",
        "compact",
        "paper"
      ],
      "primary": false
    }
  ],
  "projects": [

    {
      "name": "middleout-lattice",
      "description": "Lossless compression for model files and tensor archives with per-file and per-block codec selection.",
      "url": "https://github.com/AmSach/entropic-pegasus",
      "repoUrl": "https://github.com/AmSach/entropic-pegasus",
      "language": "Python",
      "stars": 0,
      "featured": true,
      "fork": false,
      "upstream": ""
    },    {
      "name": "bitforge",
      "description": "🔥 Shrink any LLM to fit in your pocket - Auto-compress language models for microcontrollers",
      "url": "https://github.com/AmSach/bitforge",
      "repoUrl": "https://github.com/AmSach/bitforge",
      "language": "Python",
      "stars": 1,
      "featured": true,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "btc-router",
      "description": "Bitcoin on-chain intelligence router — real-time mempool analysis, fee estimation, and UTXO optimization without a full node",
      "url": "https://github.com/AmSach/btc-router",
      "repoUrl": "https://github.com/AmSach/btc-router",
      "language": "Python",
      "stars": 0,
      "featured": true,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "compute-pool",
      "description": "Frontend for ComputePool - Decentralized Compute Grid",
      "url": "https://github.com/AmSach/compute-pool",
      "repoUrl": "https://github.com/AmSach/compute-pool",
      "language": "TypeScript",
      "stars": 0,
      "featured": true,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "datapop",
      "description": "Generate realistic synthetic tabular data with a single line of Python",
      "url": "https://github.com/AmSach/datapop",
      "repoUrl": "https://github.com/AmSach/datapop",
      "language": "Python",
      "stars": 1,
      "featured": true,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "GhostPilot",
      "description": "GPS-Denied Drone Navigation with Agentic AI - VINS-Mono + Nav2 + LLM Mission Parser",
      "url": "https://github.com/AmSach/GhostPilot",
      "repoUrl": "https://github.com/AmSach/GhostPilot",
      "language": "Python",
      "stars": 1,
      "featured": true,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "kvquant",
      "description": "Drop-in KV cache compressor for local LLM inference - Run 70B models on 8GB RAM",
      "url": "https://github.com/AmSach/kvquant",
      "repoUrl": "https://github.com/AmSach/kvquant",
      "language": "Python",
      "stars": 5,
      "featured": true,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "MeshMind",
      "description": "No public description yet.",
      "url": "https://github.com/AmSach/MeshMind",
      "repoUrl": "https://github.com/AmSach/MeshMind",
      "language": "Mixed",
      "stars": 0,
      "featured": true,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "NeuroShell",
      "description": "Convert plain English to safe shell commands using LLMs",
      "url": "https://github.com/AmSach/NeuroShell",
      "repoUrl": "https://github.com/AmSach/NeuroShell",
      "language": "Python",
      "stars": 1,
      "featured": true,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "nexus",
      "description": "OSINT engine",
      "url": "https://osnexus.vercel.app",
      "repoUrl": "https://github.com/AmSach/nexus",
      "language": "JavaScript",
      "stars": 1,
      "featured": true,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "sentience",
      "description": "Sentience - Local AI Computer. Like Zo + Claude Code, 100% on your machine.",
      "url": "https://github.com/AmSach/sentience",
      "repoUrl": "https://github.com/AmSach/sentience",
      "language": "Python",
      "stars": 2,
      "featured": true,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "sentience-final",
      "description": "Sentience v2.0 - Local AI Computer",
      "url": "https://github.com/AmSach/sentience-final",
      "repoUrl": "https://github.com/AmSach/sentience-final",
      "language": "Python",
      "stars": 0,
      "featured": true,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "Sentinel",
      "description": "aml",
      "url": "https://sentinel-three-peach.vercel.app",
      "repoUrl": "https://github.com/AmSach/Sentinel",
      "language": "JavaScript",
      "stars": 0,
      "featured": true,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "voxelnav",
      "description": "Real-time semantic voxel mapping for ROS2 robots - 100ms latency on Jetson Nano",
      "url": "https://github.com/AmSach/voxelnav",
      "repoUrl": "https://github.com/AmSach/voxelnav",
      "language": "C++",
      "stars": 17,
      "featured": true,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "WhisperBridge",
      "description": "Offline voice transcription CLI with speaker diarization - 3x faster than Whisper",
      "url": "https://github.com/AmSach/WhisperBridge",
      "repoUrl": "https://github.com/AmSach/WhisperBridge",
      "language": "Python",
      "stars": 1,
      "featured": true,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "Agada",
      "description": "ur very own medicine assistant",
      "url": "https://github.com/AmSach/Agada",
      "repoUrl": "https://github.com/AmSach/Agada",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "agadahealth",
      "description": "No public description yet.",
      "url": "https://agadahealth.vercel.app",
      "repoUrl": "https://github.com/AmSach/agadahealth",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "AmanSachanResearch",
      "description": "Aman Sachan's personal research index",
      "url": "https://github.com/AmSach/AmanSachanResearch",
      "repoUrl": "https://github.com/AmSach/AmanSachanResearch",
      "language": "Mixed",
      "stars": 0,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "amsach.github.io",
      "description": "Aman Sachan's personal research index",
      "url": "https://amsach.github.io",
      "repoUrl": "https://github.com/AmSach/amsach.github.io",
      "language": "HTML",
      "stars": 0,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "claw",
      "description": "No public description yet.",
      "url": "https://github.com/AmSach/claw",
      "repoUrl": "https://github.com/AmSach/claw",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "claw-local",
      "description": "No public description yet.",
      "url": "https://github.com/AmSach/claw-local",
      "repoUrl": "https://github.com/AmSach/claw-local",
      "language": "Mixed",
      "stars": 0,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "compute-pool-backend",
      "description": "Backend API for ComputePool",
      "url": "https://github.com/AmSach/compute-pool-backend",
      "repoUrl": "https://github.com/AmSach/compute-pool-backend",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "compute-pool-frontend",
      "description": "No public description yet.",
      "url": "https://github.com/AmSach/compute-pool-frontend",
      "repoUrl": "https://github.com/AmSach/compute-pool-frontend",
      "language": "TypeScript",
      "stars": 0,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "compute-pool-node",
      "description": "Node Agent for ComputePool - Docker image",
      "url": "https://github.com/AmSach/compute-pool-node",
      "repoUrl": "https://github.com/AmSach/compute-pool-node",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "DefSpace",
      "description": "No public description yet.",
      "url": "https://def-space.vercel.app",
      "repoUrl": "https://github.com/AmSach/DefSpace",
      "language": "HTML",
      "stars": 0,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "entropic-pegasus",
      "description": "No public description yet.",
      "url": "https://github.com/AmSach/entropic-pegasus",
      "repoUrl": "https://github.com/AmSach/entropic-pegasus",
      "language": "Python",
      "stars": 1,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "hive-fixes",
      "description": "No public description yet.",
      "url": "https://github.com/AmSach/hive-fixes",
      "repoUrl": "https://github.com/AmSach/hive-fixes",
      "language": "Python",
      "stars": 1,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "Lingua",
      "description": "Google Tranlate Translation Agent which could translate a 600 page pdf in mere seconds and reconstruct it exactly the way you input.",
      "url": "https://linguanow.vercel.app",
      "repoUrl": "https://github.com/AmSach/Lingua",
      "language": "HTML",
      "stars": 1,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "llm-foundry",
      "description": "No public description yet.",
      "url": "https://github.com/AmSach/llm-foundry",
      "repoUrl": "https://github.com/AmSach/llm-foundry",
      "language": "Python",
      "stars": 1,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "nexus-intel",
      "description": "No public description yet.",
      "url": "https://github.com/AmSach/nexus-intel",
      "repoUrl": "https://github.com/AmSach/nexus-intel",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "nexus-server",
      "description": "No public description yet.",
      "url": "https://github.com/AmSach/nexus-server",
      "repoUrl": "https://github.com/AmSach/nexus-server",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "sarva",
      "description": "Sarva — Decentralized Compute Grid",
      "url": "https://github.com/AmSach/sarva",
      "repoUrl": "https://github.com/AmSach/sarva",
      "language": "HTML",
      "stars": 0,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "sarva-backend",
      "description": "Sarva - Decentralized Compute Pool Backend",
      "url": "https://github.com/AmSach/sarva-backend",
      "repoUrl": "https://github.com/AmSach/sarva-backend",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "sarva-frontend",
      "description": "Sarva - Decentralized Compute Pool Frontend",
      "url": "https://github.com/AmSach/sarva-frontend",
      "repoUrl": "https://github.com/AmSach/sarva-frontend",
      "language": "TypeScript",
      "stars": 0,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "sarva-node",
      "description": "Sarva - Compute Pool Node Agent",
      "url": "https://github.com/AmSach/sarva-node",
      "repoUrl": "https://github.com/AmSach/sarva-node",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "sentience-v2",
      "description": "Sentience - Local AI Computer Desktop App",
      "url": "https://github.com/AmSach/sentience-v2",
      "repoUrl": "https://github.com/AmSach/sentience-v2",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "SignalHop",
      "description": "No public description yet.",
      "url": "https://github.com/AmSach/SignalHop",
      "repoUrl": "https://github.com/AmSach/SignalHop",
      "language": "Python",
      "stars": 1,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "tomcat",
      "description": "No public description yet.",
      "url": "https://tomcat-plum.vercel.app",
      "repoUrl": "https://github.com/AmSach/tomcat",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": false,
      "upstream": ""
    },
    {
      "name": "adk-python",
      "description": "An open-source, code-first Python toolkit for building, evaluating, and deploying sophisticated AI agents with flexibility and control.",
      "url": "https://google.github.io/adk-docs/",
      "repoUrl": "https://github.com/AmSach/adk-python",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "google"
    },
    {
      "name": "ansible",
      "description": "Ansible is a radically simple IT automation platform that makes your applications and systems easier to deploy and maintain. Automate everything from code deployment to network configuration to cloud management, in a language that approaches plain English, using SSH, with no agents to install on remote systems. https://docs.ansible.com.",
      "url": "https://www.ansible.com/",
      "repoUrl": "https://github.com/AmSach/ansible",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "ansible"
    },
    {
      "name": "astrbot_plugin_mnemosyne",
      "description": "一个AstrBot插件，实现基于RAG技术的长期记忆功能。",
      "url": "https://github.com/AmSach/astrbot_plugin_mnemosyne",
      "repoUrl": "https://github.com/AmSach/astrbot_plugin_mnemosyne",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "lxfight"
    },
    {
      "name": "atmos",
      "description": "👽 Terraform Orchestration Tool for DevOps. Keep environment configuration DRY with hierarchical imports of configurations, inheritance, and WAY more. Native support for Terraform and Helmfile.",
      "url": "https://atmos.tools",
      "repoUrl": "https://github.com/AmSach/atmos",
      "language": "Go",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "cloudposse"
    },
    {
      "name": "bot",
      "description": "Whiteout Survival Discord Bot that supports alliance management, event reminders, gift code redemption and more.",
      "url": "https://github.com/AmSach/bot",
      "repoUrl": "https://github.com/AmSach/bot",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "whiteout-project"
    },
    {
      "name": "Bugdom",
      "description": "🐛 Pangea Software's Bugdom for modern systems",
      "url": "https://pangeasoft.net/bug",
      "repoUrl": "https://github.com/AmSach/Bugdom",
      "language": "C",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "jorio"
    },
    {
      "name": "camelot",
      "description": "A Python library to extract tabular data from PDFs",
      "url": "https://camelot-py.readthedocs.io",
      "repoUrl": "https://github.com/AmSach/camelot",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "camelot-dev"
    },
    {
      "name": "claudemap",
      "description": "google maps for vibecoders.",
      "url": "https://github.com/AmSach/claudemap",
      "repoUrl": "https://github.com/AmSach/claudemap",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "QuinnAho"
    },
    {
      "name": "cpython",
      "description": "The Python programming language",
      "url": "https://www.python.org",
      "repoUrl": "https://github.com/AmSach/cpython",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "python"
    },
    {
      "name": "dead-domain-discovery",
      "description": "This Chromium extension scans the page for external iFrames, Scripts, and Styles, logs them to the console, and checks if their domains are resolvable.",
      "url": "https://github.com/AmSach/dead-domain-discovery",
      "repoUrl": "https://github.com/AmSach/dead-domain-discovery",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "lauritzh"
    },
    {
      "name": "DeepTutor",
      "description": "\"DeepTutor: Agent-Native Personalized Learning Assistant\"",
      "url": "http://arxiv.org/abs/2604.26962",
      "repoUrl": "https://github.com/AmSach/DeepTutor",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "HKUDS"
    },
    {
      "name": "deno",
      "description": "A modern runtime for JavaScript and TypeScript.",
      "url": "https://deno.com",
      "repoUrl": "https://github.com/AmSach/deno",
      "language": "Rust",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "denoland"
    },
    {
      "name": "deployments",
      "description": "🔖 GitHub Action for working painlessly with deployment statuses",
      "url": "https://github.com/marketplace/actions/github-deployments",
      "repoUrl": "https://github.com/AmSach/deployments",
      "language": "TypeScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "bobheadxi"
    },
    {
      "name": "Dism-Multi-language",
      "description": "Dism++ Multi-language Support & BUG Report",
      "url": "https://github.com/AmSach/Dism-Multi-language",
      "repoUrl": "https://github.com/AmSach/Dism-Multi-language",
      "language": "HTML",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "Chuyu-Team"
    },
    {
      "name": "django",
      "description": "The Web framework for perfectionists with deadlines.",
      "url": "https://www.djangoproject.com/",
      "repoUrl": "https://github.com/AmSach/django",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "django"
    },
    {
      "name": "django-tailwind-cli",
      "description": "Django and Tailwind integration based on the prebuilt Tailwind CSS CLI.",
      "url": "https://django-tailwind-cli.rtfd.io/",
      "repoUrl": "https://github.com/AmSach/django-tailwind-cli",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "django-commons"
    },
    {
      "name": "epson-printer-snmp",
      "description": "Read information and reset waste ink counters on Epson printers, using SNMP.",
      "url": "https://github.com/AmSach/epson-printer-snmp",
      "repoUrl": "https://github.com/AmSach/epson-printer-snmp",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "Zedeldi"
    },
    {
      "name": "ExceptNotifier",
      "description": "The Python package ExceptNotifier enhances the try-except statement, allowing you to receive detailed error messages via email or messenger apps.",
      "url": "https://exceptnotifier.readthedocs.io/",
      "repoUrl": "https://github.com/AmSach/ExceptNotifier",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "dsdanielpark"
    },
    {
      "name": "Frame",
      "description": "Platform for agentic - vibecoders who use claude code and codex cli",
      "url": "http://frame.cool",
      "repoUrl": "https://github.com/AmSach/Frame",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "kaanozhan"
    },
    {
      "name": "gidgethub",
      "description": "An async GitHub API library for Python",
      "url": "https://gidgethub.readthedocs.io",
      "repoUrl": "https://github.com/AmSach/gidgethub",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "gidgethub"
    },
    {
      "name": "go",
      "description": "The Go programming language",
      "url": "https://go.dev",
      "repoUrl": "https://github.com/AmSach/go",
      "language": "Go",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "golang"
    },
    {
      "name": "HeliosLauncher",
      "description": "☀ Custom launcher for modded minecraft written in Electron and Node.js",
      "url": "https://github.com/AmSach/HeliosLauncher",
      "repoUrl": "https://github.com/AmSach/HeliosLauncher",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "dscalzi"
    },
    {
      "name": "hermes-agent",
      "description": "The agent that grows with you",
      "url": "https://hermes-agent.nousresearch.com",
      "repoUrl": "https://github.com/AmSach/hermes-agent",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "NousResearch"
    },
    {
      "name": "hive",
      "description": "Multi-Agent Harness for Production AI",
      "url": "https://github.com/AmSach/hive",
      "repoUrl": "https://github.com/AmSach/hive",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "aden-hive"
    },
    {
      "name": "icom-lan",
      "description": "Python library for controlling Icom transceivers over LAN (UDP) — no wfview/hamlib required",
      "url": "https://github.com/AmSach/icom-lan",
      "repoUrl": "https://github.com/AmSach/icom-lan",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "rigplane"
    },
    {
      "name": "ics_calendar",
      "description": "Provides an ICS (icalendar) platform for the Home Assistant calendar",
      "url": "https://github.com/AmSach/ics_calendar",
      "repoUrl": "https://github.com/AmSach/ics_calendar",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "franc6"
    },
    {
      "name": "kubernetes",
      "description": "Production-Grade Container Scheduling and Management",
      "url": "https://kubernetes.io",
      "repoUrl": "https://github.com/AmSach/kubernetes",
      "language": "Go",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "kubernetes"
    },
    {
      "name": "lightweight-charts-python",
      "description": "Python framework for TradingView's Lightweight Charts JavaScript library.",
      "url": "https://github.com/AmSach/lightweight-charts-python",
      "repoUrl": "https://github.com/AmSach/lightweight-charts-python",
      "language": "TypeScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "louisnw01"
    },
    {
      "name": "MoneyPrinter-Enhanced",
      "description": "No public description yet.",
      "url": "https://github.com/AmSach/MoneyPrinter-Enhanced",
      "repoUrl": "https://github.com/AmSach/MoneyPrinter-Enhanced",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "Troptrap"
    },
    {
      "name": "monty",
      "description": "A minimal, secure Python interpreter written in Rust for use by AI",
      "url": "https://github.com/AmSach/monty",
      "repoUrl": "https://github.com/AmSach/monty",
      "language": "Rust",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "pydantic"
    },
    {
      "name": "MuseScore",
      "description": "MuseScore is an open source and free music notation software. For support, contribution, bug reports, visit MuseScore.org. Fork and make pull requests!",
      "url": "https://musescore.org",
      "repoUrl": "https://github.com/AmSach/MuseScore",
      "language": "C++",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "musescore"
    },
    {
      "name": "nautobot-app-ssot",
      "description": "Single Source of Truth for Nautobot",
      "url": "https://docs.nautobot.com/projects/ssot/en/latest/",
      "repoUrl": "https://github.com/AmSach/nautobot-app-ssot",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "nautobot"
    },
    {
      "name": "next.js",
      "description": "The React Framework",
      "url": "https://nextjs.org",
      "repoUrl": "https://github.com/AmSach/next.js",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "vercel"
    },
    {
      "name": "node",
      "description": "Node.js JavaScript runtime ✨🐢🚀✨",
      "url": "https://nodejs.org",
      "repoUrl": "https://github.com/AmSach/node",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "nodejs"
    },
    {
      "name": "node-todo",
      "description": "A simple Node/MongoDB/Angular todo app",
      "url": "https://scotch.io/tutorials/creating-a-single-page-todo-app-with-node-and-angular",
      "repoUrl": "https://github.com/AmSach/node-todo",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "scotch-io"
    },
    {
      "name": "nodejs-goof",
      "description": "Super vulnerable todo list application",
      "url": "https://github.com/AmSach/nodejs-goof",
      "repoUrl": "https://github.com/AmSach/nodejs-goof",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "snyk-labs"
    },
    {
      "name": "openssl",
      "description": "General purpose TLS and crypto library",
      "url": "https://openssl-library.org/",
      "repoUrl": "https://github.com/AmSach/openssl",
      "language": "C",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "openssl"
    },
    {
      "name": "pandas",
      "description": "Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more",
      "url": "https://pandas.pydata.org",
      "repoUrl": "https://github.com/AmSach/pandas",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "pandas-dev"
    },
    {
      "name": "php-src",
      "description": "The PHP Interpreter",
      "url": "https://www.php.net",
      "repoUrl": "https://github.com/AmSach/php-src",
      "language": "C",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "php"
    },
    {
      "name": "piemme",
      "description": "vibecoded vibecoding prompt manager for vibecoders",
      "url": "https://github.com/AmSach/piemme",
      "repoUrl": "https://github.com/AmSach/piemme",
      "language": "Rust",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "cartesia-one"
    },
    {
      "name": "Pokemon-Showdown-Dex",
      "description": "Pokémon Showdown's Pokédex",
      "url": "https://github.com/AmSach/Pokemon-Showdown-Dex",
      "repoUrl": "https://github.com/AmSach/Pokemon-Showdown-Dex",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "Zarel"
    },
    {
      "name": "PowerSync",
      "description": "Intelligent battery optimisation for Home Assistant. Supports a wide range of battery systems, electricity providers, and AC-coupled solar inverters. Includes EV charging coordination and a built-in LP optimiser.",
      "url": "https://powersync.cc/",
      "repoUrl": "https://github.com/AmSach/PowerSync",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "bolagnaise"
    },
    {
      "name": "project-based-learning",
      "description": "Curated list of project-based tutorials",
      "url": "https://github.com/AmSach/project-based-learning",
      "repoUrl": "https://github.com/AmSach/project-based-learning",
      "language": "Mixed",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "practical-tutorials"
    },
    {
      "name": "pydantic-ai",
      "description": "AI Agent Framework, the Pydantic way",
      "url": "https://ai.pydantic.dev",
      "repoUrl": "https://github.com/AmSach/pydantic-ai",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "pydantic"
    },
    {
      "name": "PyrateLimiter",
      "description": "⚔️Python Rate-Limiter using Leaky-Bucket Algorithm Family",
      "url": "https://pyratelimiter.readthedocs.io",
      "repoUrl": "https://github.com/AmSach/PyrateLimiter",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "vutran1710"
    },
    {
      "name": "python",
      "description": "Official Python client library for kubernetes",
      "url": "http://kubernetes.io/",
      "repoUrl": "https://github.com/AmSach/python",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "kubernetes-client"
    },
    {
      "name": "Python-100-Days",
      "description": "Python - 100天从新手到大师",
      "url": "https://github.com/AmSach/Python-100-Days",
      "repoUrl": "https://github.com/AmSach/Python-100-Days",
      "language": "Jupyter Notebook",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "jackfrued"
    },
    {
      "name": "python-genai",
      "description": "Google Gen AI Python SDK provides an interface for developers to integrate Google's generative models into their Python applications.",
      "url": "https://googleapis.github.io/python-genai/",
      "repoUrl": "https://github.com/AmSach/python-genai",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "googleapis"
    },
    {
      "name": "python-printer-escpos",
      "description": "Talk to Dot Matrix, Thermal POS printers supporting ESCPOS Specification",
      "url": "https://github.com/AmSach/python-printer-escpos",
      "repoUrl": "https://github.com/AmSach/python-printer-escpos",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "shantanubhadoria"
    },
    {
      "name": "PyVesc",
      "description": "Updated pyvesc to fix bugs and make stable for dyno work",
      "url": "https://github.com/AmSach/PyVesc",
      "repoUrl": "https://github.com/AmSach/PyVesc",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "liquidtemper"
    },
    {
      "name": "rails",
      "description": "Ruby on Rails",
      "url": "https://rubyonrails.org",
      "repoUrl": "https://github.com/AmSach/rails",
      "language": "Ruby",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "rails"
    },
    {
      "name": "react-shadcn-components",
      "description": "Production-ready React components following shadcn/ui principles. TypeScript-first, Tailwind-styled, Radix-powered. Beautiful defaults with complete customization freedom. The frontend UI toolkit for vibecoders who ship fast and own their code.",
      "url": "https://www.shadcn.io/",
      "repoUrl": "https://github.com/AmSach/react-shadcn-components",
      "language": "Mixed",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "shadcnio"
    },
    {
      "name": "redis",
      "description": "For developers, who are building real-time data-driven applications, Redis is the preferred, fastest, and most feature-rich cache, data structure server, and document and vector query engine.",
      "url": "http://redis.io",
      "repoUrl": "https://github.com/AmSach/redis",
      "language": "C",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "redis"
    },
    {
      "name": "roslyn",
      "description": "The Roslyn .NET compiler provides C# and Visual Basic languages with rich code analysis APIs.",
      "url": "https://docs.microsoft.com/dotnet/csharp/roslyn-sdk/",
      "repoUrl": "https://github.com/AmSach/roslyn",
      "language": "C#",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "dotnet"
    },
    {
      "name": "rsnapshot",
      "description": "a tool for backing up your data using rsync (if you want to get help, use https://lists.sourceforge.net/lists/listinfo/rsnapshot-discuss)",
      "url": "http://rsnapshot.org",
      "repoUrl": "https://github.com/AmSach/rsnapshot",
      "language": "Perl",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "rsnapshot"
    },
    {
      "name": "rust",
      "description": "Empowering everyone to build reliable and efficient software.",
      "url": "https://www.rust-lang.org",
      "repoUrl": "https://github.com/AmSach/rust",
      "language": "Rust",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "rust-lang"
    },
    {
      "name": "semgrep",
      "description": "Lightweight static analysis for many languages. Find bug variants with patterns that look like source code.",
      "url": "https://semgrep.dev",
      "repoUrl": "https://github.com/AmSach/semgrep",
      "language": "OCaml",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "semgrep"
    },
    {
      "name": "shadowsocks-libev",
      "description": "Bug-fix-only libev port of shadowsocks. Future development moved to shadowsocks-rust",
      "url": "https://github.com/shadowsocks/shadowsocks-rust",
      "repoUrl": "https://github.com/AmSach/shadowsocks-libev",
      "language": "C",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "shadowsocks"
    },
    {
      "name": "shap",
      "description": "A game theoretic approach to explain the output of any machine learning model.",
      "url": "https://shap.readthedocs.io",
      "repoUrl": "https://github.com/AmSach/shap",
      "language": "Jupyter Notebook",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "shap"
    },
    {
      "name": "sktime",
      "description": "A unified framework for machine learning with time series",
      "url": "https://www.sktime.net",
      "repoUrl": "https://github.com/AmSach/sktime",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "sktime"
    },
    {
      "name": "stackprinter",
      "description": "Debugging-friendly exceptions for Python",
      "url": "https://github.com/AmSach/stackprinter",
      "repoUrl": "https://github.com/AmSach/stackprinter",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "cknd"
    },
    {
      "name": "stakeout-agent",
      "description": "stakeout-agent aims to provide reusable infrastructure for building, observing, and extending agent-based workflows.",
      "url": "https://pypi.org/project/stakeout-agent/",
      "repoUrl": "https://github.com/AmSach/stakeout-agent",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "KyriakosFrang"
    },
    {
      "name": "t01-burnmap",
      "description": "No public description yet.",
      "url": "https://github.com/AmSach/t01-burnmap",
      "repoUrl": "https://github.com/AmSach/t01-burnmap",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "t01buddy"
    },
    {
      "name": "tensorflow",
      "description": "An Open Source Machine Learning Framework for Everyone",
      "url": "https://tensorflow.org",
      "repoUrl": "https://github.com/AmSach/tensorflow",
      "language": "C++",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "tensorflow"
    },
    {
      "name": "todoctor",
      "description": "🐍 CLI tool to analyze and report TODO comments in JavaScript and TypeScript Git repositories",
      "url": "https://todoctor.azat.io",
      "repoUrl": "https://github.com/AmSach/todoctor",
      "language": "Svelte",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "azat-io"
    },
    {
      "name": "todoman",
      "description": "✅ Simple, standards-based, command line todo (aka: task) manager.",
      "url": "https://todoman.readthedocs.io",
      "repoUrl": "https://github.com/AmSach/todoman",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "pimutils"
    },
    {
      "name": "tools",
      "description": "[mirror] Go Tools",
      "url": "https://golang.org/x/tools",
      "repoUrl": "https://github.com/AmSach/tools",
      "language": "Go",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "golang"
    },
    {
      "name": "TypeScript",
      "description": "TypeScript is a superset of JavaScript that compiles to clean JavaScript output.",
      "url": "https://www.typescriptlang.org",
      "repoUrl": "https://github.com/AmSach/TypeScript",
      "language": "TypeScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "microsoft"
    },
    {
      "name": "VibeSentry",
      "description": "Simple tools to help VibeCoders to avoid the most common security mistakes",
      "url": "https://github.com/AmSach/VibeSentry",
      "repoUrl": "https://github.com/AmSach/VibeSentry",
      "language": "Shell",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "BeyondMachines"
    },
    {
      "name": "vscode",
      "description": "Visual Studio Code",
      "url": "https://code.visualstudio.com",
      "repoUrl": "https://github.com/AmSach/vscode",
      "language": "TypeScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "microsoft"
    },
    {
      "name": "weather",
      "description": "Weather app By Using HTML, CSS, JAVASCRIPT & API",
      "url": "https://kaushalsahu07.github.io/weather/",
      "repoUrl": "https://github.com/AmSach/weather",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "kaushalsahu07"
    },
    {
      "name": "yt-dlp",
      "description": "A feature-rich command-line audio/video downloader",
      "url": "https://discord.gg/H5MNcFW63r",
      "repoUrl": "https://github.com/AmSach/yt-dlp",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "yt-dlp"
    }
  ],
  "mirrors": [
    {
      "name": "adk-python",
      "description": "An open-source, code-first Python toolkit for building, evaluating, and deploying sophisticated AI agents with flexibility and control.",
      "url": "https://google.github.io/adk-docs/",
      "repoUrl": "https://github.com/AmSach/adk-python",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "google"
    },
    {
      "name": "ansible",
      "description": "Ansible is a radically simple IT automation platform that makes your applications and systems easier to deploy and maintain. Automate everything from code deployment to network configuration to cloud management, in a language that approaches plain English, using SSH, with no agents to install on remote systems. https://docs.ansible.com.",
      "url": "https://www.ansible.com/",
      "repoUrl": "https://github.com/AmSach/ansible",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "ansible"
    },
    {
      "name": "astrbot_plugin_mnemosyne",
      "description": "一个AstrBot插件，实现基于RAG技术的长期记忆功能。",
      "url": "https://github.com/AmSach/astrbot_plugin_mnemosyne",
      "repoUrl": "https://github.com/AmSach/astrbot_plugin_mnemosyne",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "lxfight"
    },
    {
      "name": "atmos",
      "description": "👽 Terraform Orchestration Tool for DevOps. Keep environment configuration DRY with hierarchical imports of configurations, inheritance, and WAY more. Native support for Terraform and Helmfile.",
      "url": "https://atmos.tools",
      "repoUrl": "https://github.com/AmSach/atmos",
      "language": "Go",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "cloudposse"
    },
    {
      "name": "bot",
      "description": "Whiteout Survival Discord Bot that supports alliance management, event reminders, gift code redemption and more.",
      "url": "https://github.com/AmSach/bot",
      "repoUrl": "https://github.com/AmSach/bot",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "whiteout-project"
    },
    {
      "name": "Bugdom",
      "description": "🐛 Pangea Software's Bugdom for modern systems",
      "url": "https://pangeasoft.net/bug",
      "repoUrl": "https://github.com/AmSach/Bugdom",
      "language": "C",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "jorio"
    },
    {
      "name": "camelot",
      "description": "A Python library to extract tabular data from PDFs",
      "url": "https://camelot-py.readthedocs.io",
      "repoUrl": "https://github.com/AmSach/camelot",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "camelot-dev"
    },
    {
      "name": "claudemap",
      "description": "google maps for vibecoders.",
      "url": "https://github.com/AmSach/claudemap",
      "repoUrl": "https://github.com/AmSach/claudemap",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "QuinnAho"
    },
    {
      "name": "cpython",
      "description": "The Python programming language",
      "url": "https://www.python.org",
      "repoUrl": "https://github.com/AmSach/cpython",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "python"
    },
    {
      "name": "dead-domain-discovery",
      "description": "This Chromium extension scans the page for external iFrames, Scripts, and Styles, logs them to the console, and checks if their domains are resolvable.",
      "url": "https://github.com/AmSach/dead-domain-discovery",
      "repoUrl": "https://github.com/AmSach/dead-domain-discovery",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "lauritzh"
    },
    {
      "name": "DeepTutor",
      "description": "\"DeepTutor: Agent-Native Personalized Learning Assistant\"",
      "url": "http://arxiv.org/abs/2604.26962",
      "repoUrl": "https://github.com/AmSach/DeepTutor",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "HKUDS"
    },
    {
      "name": "deno",
      "description": "A modern runtime for JavaScript and TypeScript.",
      "url": "https://deno.com",
      "repoUrl": "https://github.com/AmSach/deno",
      "language": "Rust",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "denoland"
    },
    {
      "name": "deployments",
      "description": "🔖 GitHub Action for working painlessly with deployment statuses",
      "url": "https://github.com/marketplace/actions/github-deployments",
      "repoUrl": "https://github.com/AmSach/deployments",
      "language": "TypeScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "bobheadxi"
    },
    {
      "name": "Dism-Multi-language",
      "description": "Dism++ Multi-language Support & BUG Report",
      "url": "https://github.com/AmSach/Dism-Multi-language",
      "repoUrl": "https://github.com/AmSach/Dism-Multi-language",
      "language": "HTML",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "Chuyu-Team"
    },
    {
      "name": "django",
      "description": "The Web framework for perfectionists with deadlines.",
      "url": "https://www.djangoproject.com/",
      "repoUrl": "https://github.com/AmSach/django",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "django"
    },
    {
      "name": "django-tailwind-cli",
      "description": "Django and Tailwind integration based on the prebuilt Tailwind CSS CLI.",
      "url": "https://django-tailwind-cli.rtfd.io/",
      "repoUrl": "https://github.com/AmSach/django-tailwind-cli",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "django-commons"
    },
    {
      "name": "epson-printer-snmp",
      "description": "Read information and reset waste ink counters on Epson printers, using SNMP.",
      "url": "https://github.com/AmSach/epson-printer-snmp",
      "repoUrl": "https://github.com/AmSach/epson-printer-snmp",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "Zedeldi"
    },
    {
      "name": "ExceptNotifier",
      "description": "The Python package ExceptNotifier enhances the try-except statement, allowing you to receive detailed error messages via email or messenger apps.",
      "url": "https://exceptnotifier.readthedocs.io/",
      "repoUrl": "https://github.com/AmSach/ExceptNotifier",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "dsdanielpark"
    },
    {
      "name": "Frame",
      "description": "Platform for agentic - vibecoders who use claude code and codex cli",
      "url": "http://frame.cool",
      "repoUrl": "https://github.com/AmSach/Frame",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "kaanozhan"
    },
    {
      "name": "gidgethub",
      "description": "An async GitHub API library for Python",
      "url": "https://gidgethub.readthedocs.io",
      "repoUrl": "https://github.com/AmSach/gidgethub",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "gidgethub"
    },
    {
      "name": "go",
      "description": "The Go programming language",
      "url": "https://go.dev",
      "repoUrl": "https://github.com/AmSach/go",
      "language": "Go",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "golang"
    },
    {
      "name": "HeliosLauncher",
      "description": "☀ Custom launcher for modded minecraft written in Electron and Node.js",
      "url": "https://github.com/AmSach/HeliosLauncher",
      "repoUrl": "https://github.com/AmSach/HeliosLauncher",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "dscalzi"
    },
    {
      "name": "hermes-agent",
      "description": "The agent that grows with you",
      "url": "https://hermes-agent.nousresearch.com",
      "repoUrl": "https://github.com/AmSach/hermes-agent",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "NousResearch"
    },
    {
      "name": "hive",
      "description": "Multi-Agent Harness for Production AI",
      "url": "https://github.com/AmSach/hive",
      "repoUrl": "https://github.com/AmSach/hive",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "aden-hive"
    },
    {
      "name": "icom-lan",
      "description": "Python library for controlling Icom transceivers over LAN (UDP) — no wfview/hamlib required",
      "url": "https://github.com/AmSach/icom-lan",
      "repoUrl": "https://github.com/AmSach/icom-lan",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "rigplane"
    },
    {
      "name": "ics_calendar",
      "description": "Provides an ICS (icalendar) platform for the Home Assistant calendar",
      "url": "https://github.com/AmSach/ics_calendar",
      "repoUrl": "https://github.com/AmSach/ics_calendar",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "franc6"
    },
    {
      "name": "kubernetes",
      "description": "Production-Grade Container Scheduling and Management",
      "url": "https://kubernetes.io",
      "repoUrl": "https://github.com/AmSach/kubernetes",
      "language": "Go",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "kubernetes"
    },
    {
      "name": "lightweight-charts-python",
      "description": "Python framework for TradingView's Lightweight Charts JavaScript library.",
      "url": "https://github.com/AmSach/lightweight-charts-python",
      "repoUrl": "https://github.com/AmSach/lightweight-charts-python",
      "language": "TypeScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "louisnw01"
    },
    {
      "name": "MoneyPrinter-Enhanced",
      "description": "No public description yet.",
      "url": "https://github.com/AmSach/MoneyPrinter-Enhanced",
      "repoUrl": "https://github.com/AmSach/MoneyPrinter-Enhanced",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "Troptrap"
    },
    {
      "name": "monty",
      "description": "A minimal, secure Python interpreter written in Rust for use by AI",
      "url": "https://github.com/AmSach/monty",
      "repoUrl": "https://github.com/AmSach/monty",
      "language": "Rust",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "pydantic"
    },
    {
      "name": "MuseScore",
      "description": "MuseScore is an open source and free music notation software. For support, contribution, bug reports, visit MuseScore.org. Fork and make pull requests!",
      "url": "https://musescore.org",
      "repoUrl": "https://github.com/AmSach/MuseScore",
      "language": "C++",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "musescore"
    },
    {
      "name": "nautobot-app-ssot",
      "description": "Single Source of Truth for Nautobot",
      "url": "https://docs.nautobot.com/projects/ssot/en/latest/",
      "repoUrl": "https://github.com/AmSach/nautobot-app-ssot",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "nautobot"
    },
    {
      "name": "next.js",
      "description": "The React Framework",
      "url": "https://nextjs.org",
      "repoUrl": "https://github.com/AmSach/next.js",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "vercel"
    },
    {
      "name": "node",
      "description": "Node.js JavaScript runtime ✨🐢🚀✨",
      "url": "https://nodejs.org",
      "repoUrl": "https://github.com/AmSach/node",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "nodejs"
    },
    {
      "name": "node-todo",
      "description": "A simple Node/MongoDB/Angular todo app",
      "url": "https://scotch.io/tutorials/creating-a-single-page-todo-app-with-node-and-angular",
      "repoUrl": "https://github.com/AmSach/node-todo",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "scotch-io"
    },
    {
      "name": "nodejs-goof",
      "description": "Super vulnerable todo list application",
      "url": "https://github.com/AmSach/nodejs-goof",
      "repoUrl": "https://github.com/AmSach/nodejs-goof",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "snyk-labs"
    },
    {
      "name": "openssl",
      "description": "General purpose TLS and crypto library",
      "url": "https://openssl-library.org/",
      "repoUrl": "https://github.com/AmSach/openssl",
      "language": "C",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "openssl"
    },
    {
      "name": "pandas",
      "description": "Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more",
      "url": "https://pandas.pydata.org",
      "repoUrl": "https://github.com/AmSach/pandas",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "pandas-dev"
    },
    {
      "name": "php-src",
      "description": "The PHP Interpreter",
      "url": "https://www.php.net",
      "repoUrl": "https://github.com/AmSach/php-src",
      "language": "C",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "php"
    },
    {
      "name": "piemme",
      "description": "vibecoded vibecoding prompt manager for vibecoders",
      "url": "https://github.com/AmSach/piemme",
      "repoUrl": "https://github.com/AmSach/piemme",
      "language": "Rust",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "cartesia-one"
    },
    {
      "name": "Pokemon-Showdown-Dex",
      "description": "Pokémon Showdown's Pokédex",
      "url": "https://github.com/AmSach/Pokemon-Showdown-Dex",
      "repoUrl": "https://github.com/AmSach/Pokemon-Showdown-Dex",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "Zarel"
    },
    {
      "name": "PowerSync",
      "description": "Intelligent battery optimisation for Home Assistant. Supports a wide range of battery systems, electricity providers, and AC-coupled solar inverters. Includes EV charging coordination and a built-in LP optimiser.",
      "url": "https://powersync.cc/",
      "repoUrl": "https://github.com/AmSach/PowerSync",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "bolagnaise"
    },
    {
      "name": "project-based-learning",
      "description": "Curated list of project-based tutorials",
      "url": "https://github.com/AmSach/project-based-learning",
      "repoUrl": "https://github.com/AmSach/project-based-learning",
      "language": "Mixed",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "practical-tutorials"
    },
    {
      "name": "pydantic-ai",
      "description": "AI Agent Framework, the Pydantic way",
      "url": "https://ai.pydantic.dev",
      "repoUrl": "https://github.com/AmSach/pydantic-ai",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "pydantic"
    },
    {
      "name": "PyrateLimiter",
      "description": "⚔️Python Rate-Limiter using Leaky-Bucket Algorithm Family",
      "url": "https://pyratelimiter.readthedocs.io",
      "repoUrl": "https://github.com/AmSach/PyrateLimiter",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "vutran1710"
    },
    {
      "name": "python",
      "description": "Official Python client library for kubernetes",
      "url": "http://kubernetes.io/",
      "repoUrl": "https://github.com/AmSach/python",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "kubernetes-client"
    },
    {
      "name": "Python-100-Days",
      "description": "Python - 100天从新手到大师",
      "url": "https://github.com/AmSach/Python-100-Days",
      "repoUrl": "https://github.com/AmSach/Python-100-Days",
      "language": "Jupyter Notebook",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "jackfrued"
    },
    {
      "name": "python-genai",
      "description": "Google Gen AI Python SDK provides an interface for developers to integrate Google's generative models into their Python applications.",
      "url": "https://googleapis.github.io/python-genai/",
      "repoUrl": "https://github.com/AmSach/python-genai",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "googleapis"
    },
    {
      "name": "python-printer-escpos",
      "description": "Talk to Dot Matrix, Thermal POS printers supporting ESCPOS Specification",
      "url": "https://github.com/AmSach/python-printer-escpos",
      "repoUrl": "https://github.com/AmSach/python-printer-escpos",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "shantanubhadoria"
    },
    {
      "name": "PyVesc",
      "description": "Updated pyvesc to fix bugs and make stable for dyno work",
      "url": "https://github.com/AmSach/PyVesc",
      "repoUrl": "https://github.com/AmSach/PyVesc",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "liquidtemper"
    },
    {
      "name": "rails",
      "description": "Ruby on Rails",
      "url": "https://rubyonrails.org",
      "repoUrl": "https://github.com/AmSach/rails",
      "language": "Ruby",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "rails"
    },
    {
      "name": "react-shadcn-components",
      "description": "Production-ready React components following shadcn/ui principles. TypeScript-first, Tailwind-styled, Radix-powered. Beautiful defaults with complete customization freedom. The frontend UI toolkit for vibecoders who ship fast and own their code.",
      "url": "https://www.shadcn.io/",
      "repoUrl": "https://github.com/AmSach/react-shadcn-components",
      "language": "Mixed",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "shadcnio"
    },
    {
      "name": "redis",
      "description": "For developers, who are building real-time data-driven applications, Redis is the preferred, fastest, and most feature-rich cache, data structure server, and document and vector query engine.",
      "url": "http://redis.io",
      "repoUrl": "https://github.com/AmSach/redis",
      "language": "C",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "redis"
    },
    {
      "name": "roslyn",
      "description": "The Roslyn .NET compiler provides C# and Visual Basic languages with rich code analysis APIs.",
      "url": "https://docs.microsoft.com/dotnet/csharp/roslyn-sdk/",
      "repoUrl": "https://github.com/AmSach/roslyn",
      "language": "C#",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "dotnet"
    },
    {
      "name": "rsnapshot",
      "description": "a tool for backing up your data using rsync (if you want to get help, use https://lists.sourceforge.net/lists/listinfo/rsnapshot-discuss)",
      "url": "http://rsnapshot.org",
      "repoUrl": "https://github.com/AmSach/rsnapshot",
      "language": "Perl",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "rsnapshot"
    },
    {
      "name": "rust",
      "description": "Empowering everyone to build reliable and efficient software.",
      "url": "https://www.rust-lang.org",
      "repoUrl": "https://github.com/AmSach/rust",
      "language": "Rust",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "rust-lang"
    },
    {
      "name": "semgrep",
      "description": "Lightweight static analysis for many languages. Find bug variants with patterns that look like source code.",
      "url": "https://semgrep.dev",
      "repoUrl": "https://github.com/AmSach/semgrep",
      "language": "OCaml",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "semgrep"
    },
    {
      "name": "shadowsocks-libev",
      "description": "Bug-fix-only libev port of shadowsocks. Future development moved to shadowsocks-rust",
      "url": "https://github.com/shadowsocks/shadowsocks-rust",
      "repoUrl": "https://github.com/AmSach/shadowsocks-libev",
      "language": "C",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "shadowsocks"
    },
    {
      "name": "shap",
      "description": "A game theoretic approach to explain the output of any machine learning model.",
      "url": "https://shap.readthedocs.io",
      "repoUrl": "https://github.com/AmSach/shap",
      "language": "Jupyter Notebook",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "shap"
    },
    {
      "name": "sktime",
      "description": "A unified framework for machine learning with time series",
      "url": "https://www.sktime.net",
      "repoUrl": "https://github.com/AmSach/sktime",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "sktime"
    },
    {
      "name": "stackprinter",
      "description": "Debugging-friendly exceptions for Python",
      "url": "https://github.com/AmSach/stackprinter",
      "repoUrl": "https://github.com/AmSach/stackprinter",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "cknd"
    },
    {
      "name": "stakeout-agent",
      "description": "stakeout-agent aims to provide reusable infrastructure for building, observing, and extending agent-based workflows.",
      "url": "https://pypi.org/project/stakeout-agent/",
      "repoUrl": "https://github.com/AmSach/stakeout-agent",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "KyriakosFrang"
    },
    {
      "name": "t01-burnmap",
      "description": "No public description yet.",
      "url": "https://github.com/AmSach/t01-burnmap",
      "repoUrl": "https://github.com/AmSach/t01-burnmap",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "t01buddy"
    },
    {
      "name": "tensorflow",
      "description": "An Open Source Machine Learning Framework for Everyone",
      "url": "https://tensorflow.org",
      "repoUrl": "https://github.com/AmSach/tensorflow",
      "language": "C++",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "tensorflow"
    },
    {
      "name": "todoctor",
      "description": "🐍 CLI tool to analyze and report TODO comments in JavaScript and TypeScript Git repositories",
      "url": "https://todoctor.azat.io",
      "repoUrl": "https://github.com/AmSach/todoctor",
      "language": "Svelte",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "azat-io"
    },
    {
      "name": "todoman",
      "description": "✅ Simple, standards-based, command line todo (aka: task) manager.",
      "url": "https://todoman.readthedocs.io",
      "repoUrl": "https://github.com/AmSach/todoman",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "pimutils"
    },
    {
      "name": "tools",
      "description": "[mirror] Go Tools",
      "url": "https://golang.org/x/tools",
      "repoUrl": "https://github.com/AmSach/tools",
      "language": "Go",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "golang"
    },
    {
      "name": "TypeScript",
      "description": "TypeScript is a superset of JavaScript that compiles to clean JavaScript output.",
      "url": "https://www.typescriptlang.org",
      "repoUrl": "https://github.com/AmSach/TypeScript",
      "language": "TypeScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "microsoft"
    },
    {
      "name": "VibeSentry",
      "description": "Simple tools to help VibeCoders to avoid the most common security mistakes",
      "url": "https://github.com/AmSach/VibeSentry",
      "repoUrl": "https://github.com/AmSach/VibeSentry",
      "language": "Shell",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "BeyondMachines"
    },
    {
      "name": "vscode",
      "description": "Visual Studio Code",
      "url": "https://code.visualstudio.com",
      "repoUrl": "https://github.com/AmSach/vscode",
      "language": "TypeScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "microsoft"
    },
    {
      "name": "weather",
      "description": "Weather app By Using HTML, CSS, JAVASCRIPT & API",
      "url": "https://kaushalsahu07.github.io/weather/",
      "repoUrl": "https://github.com/AmSach/weather",
      "language": "JavaScript",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "kaushalsahu07"
    },
    {
      "name": "yt-dlp",
      "description": "A feature-rich command-line audio/video downloader",
      "url": "https://discord.gg/H5MNcFW63r",
      "repoUrl": "https://github.com/AmSach/yt-dlp",
      "language": "Python",
      "stars": 0,
      "featured": false,
      "fork": true,
      "upstream": "yt-dlp"
    }
  ]
};
